:command -nargs=? Test call cpbooster#CpboosterTest(<f-args>)
:command -nargs=? Debug call cpbooster#CpboosterDebug(<f-args>)
:command -nargs=? Create call cpbooster#CpboosterCreate(<f-args>)
:command -nargs=? Rtest call cpbooster#CpboosterRTest(<f-args>)
:command -nargs=? Rdebug call cpbooster#CpboosterRDebug(<f-args>)
